### ISSUE TITLE
'MolViewer' object has no attribute 'fetch'

### ISSUE THREAD

**Issue by BastiaanBergman** [cxhernandez/ipymol#17]
I get an error while reproducing the basic example:

```
from ipymol import viewer as pymol
pymol.start()
pymol.fetch('3odu')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-fd1eff913b24> in <module>()
----> 1 pymol.fetch('3odu') # Fetch PDB

AttributeError: 'MolViewer' object has no attribute 'fetch'
```

I have MacOS,
PyMOL(TM) Molecular Graphics System, Version 2.2.0.
Python 3.6.4 |Anaconda custom (64-bit)
and Jupyter 4.4.0

**Comment by cxhernandez** [comment]
Not 100% certain, but I think this is related to https://github.com/cxhernandez/ipymol/issues/14#issuecomment-361420144. Not sure when Schrödinger is releasing a fix for this. In the meantime, maybe a more helpful error message is needed,

**Comment by diallobakary4** [comment]
I am having the same problem
I had to resort to this container-based of PyMol: https://github.com/ocramz/jupyter-docker-pymol

**Comment by smheidrich** [comment]
This happens for me as well if I use the IPyMOL version from PyPI (0.5, released December 2016), but it seems to have been fixed in the current revision on Github.

**Comment by iwatobipen** [comment]
I made PR for the issue. I think calling self._add_methods() will solve the issue.
https://github.com/cxhernandez/ipymol/pull/18
