### ISSUE TITLE
TypeError: Image data can not convert to float

### ISSUE THREAD

**Issue by EvdH0** [cxhernandez/ipymol#4]
Hi!

I tried running your example

```
from ipymol import viewer as pymol
pymol.start()   # Start PyMOL RPC server
pymol.do('fetch 3odu; as cartoon; bg white')
pymol.show()
```

However I'm getting this error back

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-c835fa6be17f> in <module>()
      2 pymol.start()   # Start PyMOL RPC server
      3 pymol.do('fetch 3odu; as cartoon; bg white')
----> 4 pymol.show()
      5 pymol.show()

/Users/me/anaconda/lib/python2.7/site-packages/ipymol/core.pyc in show(self)
    107         ax = fig.add_subplot(111)
    108         ax.axis('off')
--> 109         ax.imshow(np.asarray(self.to_png()))
    110         return fig
    111 

/Users/me/anaconda/lib/python2.7/site-packages/matplotlib/axes.pyc in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   7298                        filterrad=filterrad, resample=resample, **kwargs)
   7299 
-> 7300         im.set_data(X)
   7301         im.set_alpha(alpha)
   7302         self._set_artist_props(im)

/Users/me/anaconda/lib/python2.7/site-packages/matplotlib/image.pyc in set_data(self, A)
    423         if (self._A.dtype != np.uint8 and
    424             not np.can_cast(self._A.dtype, np.float)):
--> 425             raise TypeError("Image data can not convert to float")
    426 
    427         if (self._A.ndim not in (2, 3) or

TypeError: Image data can not convert to float
```

I tried both matplotlib 1.3.1 and 1.4.2 but without success, I did had to install libpng1.5 instead of libpng1.6 because of some issues that I couldn't fix quickly (https://github.com/matplotlib/matplotlib/issues/3416/)

The problem is not in pymol since a png dump gets rendered in /var/ 
![image](https://cloud.githubusercontent.com/assets/5472957/9723352/961010ac-55bf-11e5-99e5-8f947586931a.png)

Thanks!

**Comment by EvdH0** [comment]
Kind of solved it, the problem is with the Image.  

In core.py force Image to load from PIL and it works

```
#from ipymol.compat import Image

from PIL import Image
```

**Comment by cxhernandez** [comment]
Thanks for finding this bug, @EvdH0! 

Would you like to make a pull request? I think the simplest solution is to modify [compat.py](https://github.com/cxhernandez/ipymol/blob/master/src/ipymol/compat.py):

```
try:
    import Image
except ImportError:
    from PIL import Image
```

change to

```
try:
    from PIL import Image
except ImportError:
    import Image
```

**Comment by c1rdan** [comment]
Hi, I did the modifications on compat.py, and then I also tried adding Image directly on core.py, but I'm still having exactly the same issue.

My traceback:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-dcfffd9fba90> in <module>()
----> 1 fig = pymol.show()

/home/letofran/.local/lib/python3.5/site-packages/ipymol/core.py in show(self)
    107         ax = fig.add_subplot(111)
    108         ax.axis('off')
--> 109         ax.imshow(np.asarray(self.to_png()))
    110         return fig
    111 

/home/letofran/.local/lib/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1810                     warnings.warn(msg % (label_namer, func.__name__),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, *args, **kwargs)
   1813         pre_doc = inner.__doc__
   1814         if pre_doc is None:

/home/letofran/.local/lib/python3.5/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   4945                               resample=resample, **kwargs)
   4946 
-> 4947         im.set_data(X)
   4948         im.set_alpha(alpha)
   4949         if im.get_clip_path() is None:

/home/letofran/.local/lib/python3.5/site-packages/matplotlib/image.py in set_data(self, A)
    447         if (self._A.dtype != np.uint8 and
    448                 not np.can_cast(self._A.dtype, np.float)):
--> 449             raise TypeError("Image data can not convert to float")
    450 
    451         if (self._A.ndim not in (2, 3) or

TypeError: Image data can not convert to float
```

Anybody know what may be happening? Notice I'm using Python3.5

**Comment by arpita8** [comment]
<img width="463" alt="screen shot 2017-01-03 at 4 40 49 pm" src="https://cloud.githubusercontent.com/assets/22601715/21624165/e07e5c7a-d1d3-11e6-977e-f38b9b29d39c.png">
 i am new to open cv, how can i recover this error

**Comment by cxhernandez** [comment]
@arpita8: You might find @EvdH0's solution in https://github.com/cxhernandez/ipymol/issues/4#issuecomment-138492962 to be helpful. Otherwise, I suggest you open a separate issue with the folks at [Pillow](https://github.com/python-pillow/Pillow), as this question is not pertinent to this package.

**Comment by Muzammilrajput** [comment]
1591         bound = new_sig.bind(ax, *args, **kwargs)

~\Anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*args, **kwargs)
    367                 f"%(removal)s.  If any parameter follows {name!r}, they "
    368                 f"should be pass as keyword, not positionally.")
--> 369         return func(*args, **kwargs)
    370 
    371     return wrapper

~\Anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*args, **kwargs)
    367                 f"%(removal)s.  If any parameter follows {name!r}, they "
    368                 f"should be pass as keyword, not positionally.")
--> 369         return func(*args, **kwargs)
    370 
    371     return wrapper

~\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5658                               resample=resample, **kwargs)
   5659 
-> 5660         im.set_data(X)
   5661         im.set_alpha(alpha)
   5662         if im.get_clip_path() is None:

~\Anaconda3\lib\site-packages\matplotlib\image.py in set_data(self, A)
    676                 not np.can_cast(self._A.dtype, float, "same_kind")):
    677             raise TypeError("Image data of dtype {} cannot be converted to "
--> 678                             "float".format(self._A.dtype))
    679 
    680         if not (self._A.ndim == 2

TypeError: Image data of dtype object cannot be converted to float

> `any body know the this error????`
